on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    services:
      artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:7.12.10
        ports:
          - 8081:8081
    steps:
      - name: Check out action
        uses: actions/checkout@v4
      - name: Create artifacts to deploy
        run: |
          mkdir -p deployment-repository/com/example/module-a/1.0.0-SNAPSHOT
          touch deployment-repository/com/example/module-a/1.0.0-SNAPSHOT/module-a-1.0.0-SNAPSHOT.jar
          touch deployment-repository/com/example/module-a/1.0.0-SNAPSHOT/module-a-1.0.0-SNAPSHOT.pom
          touch deployment-repository/com/example/module-a/1.0.0-SNAPSHOT/module-a-1.0.0-SNAPSHOT-sources.jar
          touch deployment-repository/com/example/module-a/1.0.0-SNAPSHOT/module-a-1.0.0-SNAPSHOT-javadoc.jar
          mkdir -p deployment-repository/com/example/module-b/1.0.0-SNAPSHOT
          touch deployment-repository/com/example/module-b/1.0.0-SNAPSHOT/module-b-1.0.0-SNAPSHOT.jar
          touch deployment-repository/com/example/module-b/1.0.0-SNAPSHOT/module-b-1.0.0-SNAPSHOT.pom
          touch deployment-repository/com/example/module-b/1.0.0-SNAPSHOT/module-b-1.0.0-SNAPSHOT-sources.jar
          touch deployment-repository/com/example/module-b/1.0.0-SNAPSHOT/module-b-1.0.0-SNAPSHOT-javadoc.jar
      - name: Run action
        uses: ./
        id: run
        with:
          uri: 'http://artifactory:8081/artifactory'
          username: 'admin'
          password: 'password'
          build-name: ${{github.action}}
          repository: 'example-repo-local'
          folder: 'deployment-repository'
      - name: Download artifacts
        run: |
          wget http://artifactory:8081/artifactory/example-repo-local/com/example/module-a/1.0.0-SNAPSHOT/module-a-1.0.0-SNAPSHOT.jar
          wget http://aritfactory:8081/artifactory/example-repo-local/com/example/module-b/1.0.0-SNAPSHOT/module-b-1.0.0-SNAPSHOT.jar
