on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    services:
      artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:7.12.10
        ports:
          - 8081:8081
    steps:
      - name: Check out action
        uses: actions/checkout@v4
      - name: Run action
        uses: ./
        id: run
        with:
          uri: 'http://localhost:8081/artifactory'
          username: 'admin'
          password: 'password'
          build-name: ${{github.action}}
          repository: 'example-repo-local'
          folder: 'deployment-repository'
